### ISSUE TITLE
Scrollbars in full screen mod

### ISSUE THREAD

**Issue by osresearch** [ffd8/P5LIVE#31]
![Screenshot from 2019-11-14 16-44-12](https://user-images.githubusercontent.com/3068843/68872251-06935480-06fe-11ea-9370-18b119f6150b.png)

In both firefox and chrome (on Linux) there are horizontal and vertical scrollbars in windowed or full screen mode.

**Comment by osresearch** [comment]
![Screenshot from 2019-11-14 16-56-48](https://user-images.githubusercontent.com/3068843/68873349-c9c85d00-06ff-11ea-8966-a996ed8ee734.png)

It appears that it is caused by the `p5-frame`. If I make it 50% the scrollbar stays attached to it.

**Comment by ffd8** [comment]
Not running on Linux, so I couldn't test – but just set any overflow to hidden for that p5-frame div in #34 . Could you let me know if it fixed the issue?

**Comment by ffd8** [comment]
Should be solved in all browsers – the sketch within the iFrame now has an `overflow:hidden` on it's size to make sure. Hopefully solved – will reopen if still present, but not seeing in any browser.
