### ISSUE TITLE
typo Midi Demo

### ISSUE THREAD

**Issue by RBvonRB** [ffd8/P5LIVE#47]
In the parseMidi function, it says contol, should say cont**r**ol

https://github.com/ffd8/P5LIVE/blob/7f74934ab212773ff068c15d8d03914212a9b805/includes/demos/P5L_demos.json#L185

**Comment by ffd8** [comment]
Aha good catch (was only testing with a little keyboard w/o control changes) – thanks and now fixed.. will add to pending updates that will be pushed any day now.

**Comment by ffd8** [comment]
Fixed in #48
