### ISSUE TITLE
Console disappears instantly 

### ISSUE THREAD

**Issue by grisevg** [ffd8/P5LIVE#71]
Output to console is visible for a fraction of a second and then disappears. 
Any way to see console at all times?

**Comment by ffd8** [comment]
Good point – in the VJ context, I wanted the console to go away as quickly as possible (if it was just a warning or FES) – but of course, there's tiimes when it's nice to debug more. FYI, if calling `print()` in the draw, it stays visible. There's also a 'prevent flooding' of the console, so if it's the same message, ie `print('hello world')` or a variable that doesn't change, the actual console only prints once.. but `print(frameCount)` would show every number.

I can imagine changing the `settings » console` to just have a drop-down menu with the options: `auto`, `on`, `off` or similar.. default being `auto`.

- [ ]  - to be added with next update...

**Comment by ffd8** [comment]
@grisevg – FYI, the latest update, 1.5.0, allows you to have the console always visible! cheers
