### ISSUE TITLE
Terminal error when starting offline

### ISSUE THREAD

**Issue by aidaeloweidy** [ffd8/P5LIVE#72]
Hi. Thank you so much for creating p5-live. I've been using it problem-free for many months but a few days ago, in the command prompt when I enter 'npm start', I get this error message everytime:

C:\Users\aidah\OneDrive\Desktop\P5LIVE-main\P5LIVE-main\server.js:79
        iop = require('socket.io', {transports: ['WebSocket'] }).listen(8082);
                                                                 ^

TypeError: require(...).listen is not a function
    at Object.<anonymous> (C:\Users\aidah\OneDrive\Desktop\P5LIVE-main\P5LIVE-main\server.js:79:59)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

what could the problem be here?

**Comment by ffd8** [comment]
@aidaeloweidy Ooh that's no good! Did you chance anything in the meantime? Install other things, update system.. have other processes running parallel? Curious what could have caused the issue. FYI, this port 8082 is for OSC (open sound control) – any chance you've modified any of the files within that P5LIVE folder?

Just to be sure you have all modules (maybe loading from wrong folder), type `npm install` once within the folder, then again `npm start`.

I see you are using the file on your `OneDrive` = cloud synced folder... curious if that causes an issue?? Do you also have a local (unsynced) documents folder to test installing it in? All saved files etc, should be within your browser's `localStorage`, so it doesn't matter where P5LIVE sits,starts from, so long as it's using the same `localhost:5000` address.

**Comment by ffd8** [comment]
@desterritorializ-ada just to double check, did you first run `npm install` once while inside of that folder? I'm guessing the node_modules haven't been installed yet if it can't find the 'express' module.

**Comment by ffd8** [comment]
awesome to hear it's working now! i'm gonna close this issue, since i'm guessing it's been resolved as well for @aidaeloweidy - otherwise, just reopen it with another comment.
