### ISSUE TITLE
Data stored in offline mode missing

### ISSUE THREAD

**Issue by nitchafame** [ffd8/P5LIVE#89]
I've always been using the offline mode. 
It seems like my Chrome updated version or something. All my sketches are gone and I had backup a while back. 
Is there anyway to restore the sketch if this happened

**Comment by ffd8** [comment]
Eeek - sorry to hear about a chrome update causing that?! I'm always hesitant to update and luckily haven't had any data-loss the last few updates. Hopefully your offline version was set to auto-backup?? (i forget if the last version had it set to 'daily' as default?) – look inside your P5LIVE folder and see if there's a `_backups` folder sitting there? If you're lucky, there's a fairly recent save that you can drag and drop into the window to recover everything.

**Comment by nitchafame** [comment]
Thank you! I found some of the more recent ones. 

But now every time I close Chrome all data/settings are gone too :/
I probably try downloading an older version or identify what setting causing this :(

**Comment by ffd8** [comment]
Strange - I wonder if you have a special extension installed that is clearing your browser history/data everytime you close it? I'd imagine there's the ability in chrome prefs or that extension to allow either teddavis.org (domain of p5live online) or localhost:5000 (localhost:5001 from now on) to persist?

**Comment by ffd8** [comment]
I hope this has been solved – FYI, P5LIVE v1.5.0+ now automatically sets the `backups` setting to `daily` for the offline mode (backups sit within the `/_backups/` directory of the P5LIVE folder. Online backups are still opt-in.
