### ISSUE TITLE
Visuals-only Pop-up

### ISSUE THREAD

**Issue by massoneriaminimale** [ffd8/P5LIVE#90]
Started coding few days ago with this awsome tool, i'm planning to project visuals with it.
I'm facing some frame-rate issue with the visuals-only pop up, its working really slow (nothing else running on my macbook pro 2,7 GHz i5 8go RAM).. Any advice ?

**Comment by ffd8** [comment]
@massoneriaminimale Using Visuals-only Popup runs a 2nd canvas in that 2nd window (piping the visuals across) – it sounds like your hardware may be struggling depending on what you're drawing. I'd recommend adding `pixelDensity(1)` in the setup, which prevents p5.js from using 'retina graphics' (aka, 2x bigger than you see) – things will get a bit softer, but performance should be fine.

**Comment by ffd8** [comment]
Hope lowering the `pixelDensity()` cleared it up. If still an issue, feel free to re-open this with more details.
