### ISSUE TITLE
Is cocoding broken on the main site? Resources failed to load.

### ISSUE THREAD

**Issue by TiborUdvari** [ffd8/P5LIVE#92]
I've been trying to use COCOding today, but it doesn't seem to work. As you can see there is no session info, username etc.

<img width="1136" alt="Screenshot 2024-05-06 at 15 51 05" src="https://github.com/ffd8/P5LIVE/assets/1434442/5de62001-8fce-4bdb-b92b-e08780b0067b">

I think the problem is with these libraries that are missing on the main site: 
<img width="1147" alt="Screenshot 2024-05-06 at 15 52 55" src="https://github.com/ffd8/P5LIVE/assets/1434442/6fb0217a-8626-49a5-909e-a09af41e804e">

**Comment by ffd8** [comment]
Hey @TiborUdvari – it's working again, thanks for making the issue! I thought i had the error message mention that an issue should be made if not working, but I also didn't see it.. gotta fix that. Every ~5mo or so, the cocoding server processing breaks and needs a restart.. i plan to slowly replace the whole infrastructure for cocoding with [yjs](https://github.com/yjs/yjs) which works flawlessly, but probably won't take place until upcoming summer.
