### ISSUE TITLE
"tab freeze" in chrome halts sketch after some time

### ISSUE THREAD

**Issue by kaosbeat** [ffd8/P5LIVE#96]
I have a sketch running as part of an installation. It's on a keyboardless/mouseless mac mini, connected to a large screen projection. A virgin mac mini with chrome and an offline P5Live installation.

All is working fine, but after some time the patch freezes.
connecting the Bluetooth mouse and moving it resumes the sketch.

I suspect chrome is doing "energy saving" and freezes all foreground tabs ([reference](https://www.tenforums.com/tutorials/146276-how-enable-disable-tab-freezing-google-chrome.html)) 

is there a way to keep the tab active, in code?

**Comment by ffd8** [comment]
Heyhey awesome setup – curious what you have running? 

How interesting.. haven't experienced this, even when recently exhibiting a few imacs running P5LIVE for a week long exhibition (2 of them had no user input but kept doing their thing). Have you already disabled 'eco render' in the settings panel? That pauses the p5.js sketch when the `focus` is lost from the window.. I was opening the chrome browser from terminal using the kiosk option (don't have the exact CLI command here, but it should be something like):
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome -kiosk URL_PATH_HERE`

[Some suggest](https://stackoverflow.com/a/66311152) loading it with this flag also helps (could be toggled on when the kiosk mode is used?):
`--disable-hang-monitor`

+ one more [recent SO thread](https://stackoverflow.com/questions/62140718/stop-chrome-tab-sleeping-hibernating-2020) on the subject. 

Let me know if/what works...

**Comment by kaosbeat** [comment]
Running from terminal with that exact switch --kiosk. I'll look into your
links. Osx version is Sonoma, which apparently has the power management
rehauled. I haven't used osx since long... Developed this on a linux laptop
where it ran smooth and long...

**Comment by kaosbeat** [comment]
I here's what I tried overnight.

I loaded a video (using P5s createVideo) and played it with one pixel only visible on a loop. I read somewhere (source missing) that having media playback will stop the browser from freezing.
Unfortunately the page crashed (well the popup "your page is unresponsive, wait/kill" was there when I checked)

Another thing I tried was rerunning the setup function periodically by adding 
	`setInterval(function(){ setup() },10000);`
to my setup(){}
I would do it like every hour or so but this seems to crash the page after like 10 times. Might still work as I will reboot the mac every day. This though makes me suspect I have a (tiny) memory problem somewhere in my code... but maybe it is not triggered on my 64Gb RAM computer vs the 8Gb Macmini?

I also tried completely reloading the page, but for some reason putting` setInterval(function(){window.location.reload(true);}, 1000)`
does not execute the code after a reload

The whole thing is just displaying some animated text with author names (a lot though, like 1500) for a festivity in a local book shop. I disabled the hydra layer, tried to delete and reinstance all arrays containing text particle objects, I tracked the length of my object arrays, I tried to do some memory profiling in chrome (not an expert at all). I also reduced the list of names from 1500 to 15, disabled the check for dublkicate names on screen and still get the same behaviour. Which again makes me think there is a performance issue. Drafting a minimal crash example now

**Comment by kaosbeat** [comment]
Ok I went ahead and deleted about everything. it still crashes...
I tried it with one of the official examples (_canvas_small)  
Continuously rerunning the setup function always crashes P5Live  
// setInterval(function(){ setup() },1000); .

**Comment by kaosbeat** [comment]
I finally I wrote an applescript that kills and starts chrome every hour,
short flash, but seems to solve the problem.
You can do chrome://restart from the address bar, but unfortunately not
from javascript itself
I was thinking along  the lines of using an older chromium/P5js but haven't
tried it, as I had similar problems in firefox

the chromium lectron wrapper seems a good idea, gonna check that out.
Thanks for helping out

Just a reminder that chrome/firefox always seem to crash when rerunning
setup() 10 times in a row... That might have been an issue thta was
overlooked earlier, but came up as I tried it as one of the solutions..
some memory cleanup not being done on hard recompile?

**Comment by ffd8** [comment]
Somehow haven't had any issues with this at all – also in an installation that ran for a week (auto turned on/off each day) – across 3x 2020 iMacs running Ventura and Sonoma... really curious what might be causing it.. as it only happens on your MacMini and not on your laptop – curious what else is happening on that machine? Or also on laptop?

If going electron route, definitely [add flags to prevent caching](https://stackoverflow.com/a/55026131) as you develop it.

And with `setup()` crashing if ran multiple times.. I wonder what is taking place in there that could be causing an issue when re-generating. I just tested calling it every few seconds from the draw() and no issue.. also double checked iFrame wasn't producing multiple canvases – but was replacing them. Whenever triggering a 'hardCompile' – it replaces the entire iframe contents, so nothing lingers. One can also just toss specific contents wanted from the `setup()` into a `customInit()` function that is called inside the setup and again on demand... that way `createCanvas()` and any other 1x only functions don't get called?

Last but not least, you can also call a hardCompile from your code (perhaps with a `setInterval` for every x minutes/hours): `parent.recompile()`

Would be great to know if there's any other memory cleanup issues being missed.. but hope it works out and if you can isolate the issue and share some code that causes it, would be happy to look into it. Until then, I'm guessing we can close this?

**Comment by kaosbeat** [comment]
Ok, 
I'm learning a lot here, I was not able to isolate the issue
The installation seems to be running fine for a couple of days already. Not touching it now :-)
so access to a mac also for now.
But I'll remember tot test this earlier on the next time...
maybe the 4K resolution is not a good Idea after all

**Comment by ffd8** [comment]
Glad to hear and hope it works out well – feel free to share later a docu of the setup, very curious what it's doing.

+ aha, 4K display. I don't have such experience.. curious when it's sending to that, if it's still 2x/retina the graphics to such a display (why `pixelDensity(1)` is important if performance is an issue, otherwise the canvas is 2x larger than you think).

**Comment by ffd8** [comment]
Randomly was searching Chrome preferences to disable something when I stumbled across this setting I made at some point in the past, noo idea when:

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/e09215de-e937-4a78-8bb6-7d252612b24c">

I'm curious if you had also added your localhost for P5LIVE to such a list?

**Comment by kaosbeat** [comment]
Yes I did.
Meanwhile the installation is still running fine. I think it maybe has to
do with the amount of data I'm preloading? Although it's in the order of
kilobytes, it is creating particles out of it, and maybe copies them to
memory...
Already on the next project and that seems to be running fine on raspberry
pi4. Only difference is the data loaded
